---
title: "Drop_Seq_leaf"
author: "Chenxin Li"
date: "5/16/2022"
output:  
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(tidyverse)
library(Seurat) 
library(readxl)
library(RColorBrewer)
library(viridis)
library(svglite) 
library(patchwork)
library(cowplot)
```

# Load data
```{r}
Dropseq_raw <- read_delim("../Data/single_cell_matrix/AA_AB/cro_aa_ab_DEG.txt",
                          delim = "\t", escape_double = F, trim_ws = T, col_types = cols())
```

# Set up Seurat object
```{r}
Drop_seq <- CreateSeuratObject(counts = Dropseq_raw[, -1], min.cells = 3, min.features = 200, project = "Drop-seq", row.names = Dropseq_raw$GENE) 
```

# QC and cell selection
 
```{r}
blank <- data.frame(
  x = 1:10000,
  y = 1:10000
) %>% 
  ggplot(aes(x = x, y = y)) +
  theme_void()
```

```{r}
Drop_scatter <- Drop_seq@meta.data %>% 
  ggplot(aes(x = nCount_RNA, y = nFeature_RNA)) +
  geom_point(alpha = 0.5) +
  geom_vline(xintercept = 300, color = "red2") +
  geom_vline(xintercept = 10000, color = "red2") +
  geom_hline(yintercept = 250, color = "blue1") +
  geom_hline(yintercept = 3000, color = "blue1") +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()

Drop_hist1 <- Drop_seq@meta.data %>% 
  ggplot(aes(x = nCount_RNA)) +
  geom_histogram(bins = 100) +
  geom_vline(xintercept = 300, color = "red2") +
  geom_vline(xintercept = 10000, color = "red2") +
  scale_x_log10() +
  theme_classic()

Drop_hist2 <- Drop_seq@meta.data %>% 
  ggplot(aes(x = nFeature_RNA)) +
  geom_histogram(bins = 100) +
  geom_vline(xintercept = 250, color = "blue1") +
  geom_vline(xintercept = 3000, color = "blue1") +
  scale_x_log10() +
  theme_classic() +
  coord_flip()

wrap_plots(
  Drop_hist1, blank,
  Drop_scatter, Drop_hist2,
  nrow = 2, ncol = 2, 
  widths = c(1, 0.2), 
  heights = c(0.2, 1)
)

ggsave("../Results/R_output_Leaf_scRNAseq/Drop_seq_filtering.svg", height = 4, width = 5, bg = "white")
ggsave("../Results/R_output_Leaf_scRNAseq/Drop_seq_filtering.png", height = 4, width = 5, bg = "white")
```

```{r}
Drop_seq <- subset(Drop_seq, subset = nFeature_RNA > 250 &
                     nFeature_RNA < 3000 &
                     nCount_RNA > 300 &
                     nCount_RNA < 10000) 

summary(Drop_seq$nFeature_RNA)
summary(Drop_seq$nCount_RNA)
```


# Normalize 
```{r}
Drop_seq <- NormalizeData(Drop_seq, normalization.method = "LogNormalize", scale.factor = 10000)
```

# Select Feature
```{r}
Drop_seq <- FindVariableFeatures(Drop_seq, selection.method = "vst", nfeatures = 3000)  
```

```{r}
VariableFeaturePlot(Drop_seq)
```
# Scale Data 
```{r}
Drop_seq <- ScaleData(Drop_seq)
```

# PCA
```{r}
Drop_seq <- RunPCA(Drop_seq, features = VariableFeatures(object = Drop_seq), verbose = F)
DimPlot(Drop_seq, reduction = "pca") +
theme(
  legend.position = "none"
)
```
# Determine dimension of data 
```{r}
ElbowPlot(Drop_seq, ndims = 50)
```
# UMAP and Find clusters 
```{r}
Drop_seq <- FindNeighbors(Drop_seq, dims = 1:30)
Drop_seq <- FindClusters(Drop_seq, resolution = 0.5)
Drop_seq <- RunUMAP(Drop_seq, dims = 1:20,
                    min.dist = 0.001, repulsion.strength = 1, n.neighbors = 30, spread = 1)
```

```{r}
UMAP1_dropseq <- DimPlot(Drop_seq, reduction = "umap", label = T, label.size = 5, repel = T) + 
  theme_void() +
  theme(
    text = element_text(size = 14, color = "black", face = "bold"),
    legend.position = "none",
    title = element_text(size = 10)
  ) +
  ggtitle("scRNA-seq with\nDrop-seq platform")

UMAP1_dropseq
```
# Identify cell types 
```{r}
leaf_markers <- read_csv("../Results/R_outputs/leaf_markers.csv")
leaf_markers <- leaf_markers %>% 
  mutate(gene = str_replace(cro.v3, "_", "-"))

head(leaf_markers)
```

```{r}
DotPlot(Drop_seq, features = unique(leaf_markers$gene), 
        ) +
  scale_color_gradientn(colors = viridis(10, option = "A")[1:9]) +
  labs(y = "Cluster",
       x = "Genes") + 
  coord_flip()
```

```{r}
leaf_marker_nicer <- read_excel("../Data/cell_type_marker_leaf.xlsx") 
leaf_marker_nicer <- leaf_marker_nicer %>% 
  mutate(gene = str_replace_all(Cro_v3, "_", "-"))

head(leaf_marker_nicer)
```

```{r}
levels(Drop_seq) <- c(
  "0", "1", "2", "4", "5",
  "3", "7", "6"
)

DotPlot(Drop_seq, features = rev(leaf_marker_nicer$gene)) +
  scale_color_gradientn(colors = viridis(10, option = "A")[1:9]) +
  labs(y = "Cluster",
       x = "Genes") + 
   theme(
     legend.position = "top",
     legend.box = "vertical"
   ) +
   coord_flip()
```
```{r}
Drop_seq_leaf_cell_type <- data.frame(
  cluster = 0:7
) %>% 
  mutate(cell_type = case_when(
    cluster == 0 | 
      cluster == 1 | 
      cluster == 2 | 
      cluster == 4 | 
      cluster == 5  ~ "Mesophyll",
    cluster == 3 ~ "Epidermis",
    #cluster == 8 ~ "Vasculature",
    cluster == 7 ~ "IPAP",
    cluster == 6 ~ "Idioblast"
  )) %>% 
  mutate(cell_type = factor(cell_type, 
                            levels = c(
                              "Mesophyll", "Epidermis",  
                              "IPAP", "Idioblast"))) %>% 
  mutate(cluster = factor(cluster, levels = c(
    "0", "1", "2", "4", "5",
  "3", "7", "6"
  )))

Drop_seq_leaf_assignment_graph <- Drop_seq_leaf_cell_type %>% 
  ggplot(aes(x = cluster, y = "")) +
  facet_wrap(~ cell_type, scales = "free", ncol = 2) +
  geom_point(size = 5, aes(color = cluster)) +
  geom_text(aes(label = cluster)) +
  labs(x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    text = element_text(size = 14, color = "black", face = "bold"),
    axis.text.x = element_blank(),
    panel.border = element_rect(color = "black", fill = NA) 
    ) 

UMAP2_dropseq <- DimPlot(Drop_seq, reduction = "umap", label = T, label.size = 5, repel = T) + 
  theme_void() +
  theme(
    text = element_text(size = 14, color = "black", face = "bold"),
    legend.position = "none",
    title = element_text(size = 10)
  ) +
  ggtitle("scRNA-seq with\nDrop-seq platform")


wrap_plots(UMAP2_dropseq, Drop_seq_leaf_assignment_graph, 
           nrow = 2, heights = c(1, 0.3))

ggsave("../Results/R_output_Leaf_scRNAseq/UMAP_Dropseq.svg", 
       height = 4.7, width = 3, bg = "white")

ggsave("../Results/R_output_Leaf_scRNAseq/UMAP_Dropseq.png", 
       height = 4.7, width = 3, bg = "white")
```

# MIA at cell type 
```{r}
Dropseq_metadata <- Drop_seq@meta.data %>% 
  mutate(barcode = row.names(Drop_seq@meta.data)) %>% 
  mutate(cell_type = case_when(
     seurat_clusters == 0 | 
      seurat_clusters == 1 | 
      seurat_clusters == 2 | 
      seurat_clusters == 4 | 
      seurat_clusters == 5  ~ "Mesophyll",
    seurat_clusters == 3 ~ "Epidermis",
    #seurat_clusters == 8 ~ "Vasculature",
    seurat_clusters == 7 ~ "IPAP",
    seurat_clusters == 6 ~ "Idioblast"
  ))

head(Dropseq_metadata)
```
```{r}
Drop_seq$cell_type <- Dropseq_metadata$cell_type

DotPlot_MIA_cell_type_Dropseq <- DotPlot(Drop_seq, 
                                 features = rev(leaf_MIA_genes$gene),
                                 group.by = "cell_type")
```

```{r}
DotPlot_MIA_cell_type_Dropseq$data %>%
  #filter(id != "Guard Cells") %>% 
  #filter(id != "Phloem CC") %>% 
  # mutate(id = factor(id, levels = c(
  #   "IPAP", "Epidermis", "Idioblast",
  #   "Mesophyll", "Vasculature", "Guard cells", "Phloem CC"
  # ))) %>%
  mutate(id2 = case_when(
    str_detect(id, "Meso") ~ "M",
    str_detect(id, "Epi") ~ "E",
    str_detect(id, "IP") ~ "IP",
    str_detect(id, "Idio") ~ "I",
    str_detect(id, "Vas") ~ "V"
  )) %>% 
  mutate(id2 = factor(id2, levels = c(
    "IP", "E", "I",
    "M", "V"
  ))) %>% 
  mutate(internal.tag = row.names(.)) %>% 
  arrange(internal.tag) %>% 
  mutate(gene = case_when(
    is.na(features.plot) ~ str_remove_all(internal.tag, "rna_"),
    T ~ features.plot %>% as.character()
  )) %>% 
  mutate(gene = str_sub(gene, start = 1, end = 13)) %>% 
  inner_join(leaf_MIA_genes, by = "gene") %>%
  mutate(tag = case_when(
    tag == "MATE" ~ "SLTr",
    T ~ tag
  )) %>% 
  mutate(gene = reorder(gene, -order)) %>%
  mutate(tag = reorder(tag, -order)) %>%
  ggplot(aes(y = tag, x = id2)) +
  geom_point(aes(size = pct.exp, fill = avg.exp.scaled), shape = 21, color = "white") +
  # scale_y_discrete(label = NULL) +
  scale_fill_viridis(option = "A", begin = 0, end = 0.8) +
  guides(size = guide_legend(override.aes = list(fill = "grey40"),
                             title.position = "top", col = 1)) +
  guides(fill = guide_colorbar(title.position = "top")) +
  labs(x = NULL,
       y = NULL, 
       fill = "Avg.\nExp.",
       size = "% Exp.") +
  #theme_minimal() +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        axis.text = element_text(color = "black"),
        axis.text.y = element_text(hjust = 0.5),
        axis.text.x = element_text(hjust = 1, angle = 45, face = "plain"),
        legend.position = "right",
        legend.box = "vertical",
        legend.key.height = unit(0.8, "lines"),
        legend.key.width = unit(0.8, "lines"),
        legend.title = element_text(size = 12),
        title = element_text(size = 10, face = "bold")) 

ggsave("../Results/R_output_Leaf_scRNAseq/MIA_at_cell_type_Drop.svg", height = 7, width = 2.8, bg = "white")
ggsave("../Results/R_output_Leaf_scRNAseq/MIA_at_cell_type_Drop.png", height = 7, width = 2.8, bg = "white")
```
### GGPS SSU

```{r}
GPPS_SSU_10x <- readRDS("../Results/R_output_Leaf_scRNAseq/GPPS_SSU_10x.Rds")
```

```{r}
GPPS_SSU_Drop <- DotPlot(Drop_seq, features = "CRO-05G001760", group.by = "cell_type") +
  scale_x_discrete(label = "GPPS SSU") +
  scale_y_discrete(label = c("E", "I", "IP", "M")) +
  scale_color_viridis(option = "A", begin = 0, end = 0.8, breaks = c(-1, 1)) +
  #scale_size_continuous(breaks = c(30, 40, 50)) +
  labs(x = NULL,
       y = NULL) +
  guides(size = guide_legend(nrow = 2, order = 1)) +
  #theme_minimal() +
  theme_classic() +
  theme(text = element_text(size = 14, color = "black"),
        axis.text = element_text(color = "black"),
        axis.text.y = element_text(angle = 90, hjust = 0.5),
        axis.text.x = element_text(hjust = 1, angle = 45, face = "plain"),
        legend.position = "top",
        legend.box = "vertical",
        legend.key.height = unit(0.8, "lines"),
        legend.key.width = unit(0.8, "lines"),
        legend.title = element_text(size = 12),
        title = element_text(size = 10, face = "bold")) +
  ggtitle("Drop-seq") +
  coord_flip()

wrap_plots(GPPS_SSU_10x, GPPS_SSU_Drop)


ggsave("../Results/R_output_Leaf_scRNAseq/GPPS_SSU_Drop.svg", width = 6, height = 3, bg = "white")
ggsave("../Results/R_output_Leaf_scRNAseq/GPPS_SSU_Drop.png", width = 6, height = 3, bg = "white")
```



# Drop-seq vs 10x
```{r}
expr.drop <- GetAssayData(Drop_seq, slot = "scale.data")

expr.drop_by_cell_type <- expr.drop %>% 
  as.data.frame() %>% 
  mutate(gene = row.names(.)) %>% 
  gather("barcode", "exp", 1:nrow(Dropseq_metadata)) %>%
  inner_join(Dropseq_metadata, by = "barcode") %>% 
  group_by(gene, cell_type) %>% 
  summarise(mean.rel.exp = mean(exp)) %>% 
  ungroup()
 

head(expr.drop_by_cell_type)
```

## Wrangle data 
```{r}
expr.leaf_10x <- readRDS("../Results/R_output_Leaf_scRNAseq/expr.leaf_by_cell_type.Rds")

head(expr.leaf_10x)
```
```{r}
Drop_wide <- expr.drop_by_cell_type %>% 
  mutate(cell_type_dropseq = paste0("dropseq", cell_type)) %>% 
  select(-cell_type) %>% 
  spread(cell_type_dropseq, mean.rel.exp) 

leaf_10X_wide <- expr.leaf_10x %>% 
  mutate(cell_type_10x = paste0("Tenx", cell_type)) %>% 
  select(-cell_type) %>% 
  spread(cell_type_10x, mean.rel.exp) 

head(Drop_wide)
head(leaf_10X_wide)
```

```{r}
Dropwide2 <- Drop_wide %>% 
  inner_join(leaf_10X_wide, by = "gene") %>% 
  select(1:5)

head(Dropwide2)

leaf_10X_wide2 <- Drop_wide %>% 
  inner_join(leaf_10X_wide, by = "gene") %>% 
  select(1, 6:ncol(.))

head(leaf_10X_wide2)
```

## Find Correlations 
```{r}
cor(Dropwide2$dropseqMesophyll, leaf_10X_wide2[-1])
```

```{r}
cor_cell_type <- function(v){
  cor(v, leaf_10X_wide2[,-1])
}

Dropseq_vs_10X <- apply(Dropwide2[,-1], MARGIN = 2, FUN = cor_cell_type) %>% 
  as.data.frame() %>% 
  mutate(TenX = colnames(leaf_10X_wide2[,-1]))

Dropseq_vs_10X
```
## visualize results 
```{r}
Dropseq_vs_10X %>% 
  gather("Dropseq_cell_type_tag", "Cor", 1:4) %>% 
  mutate(leaf_10X_cell_type = str_remove(TenX, "TenX")) %>% 
  mutate(Drop_seq_cell_type = str_remove(Dropseq_cell_type_tag, "DropSeq")) %>% 
  mutate(TenX_tag =  case_when(
    str_detect(leaf_10X_cell_type, "Meso") ~ "M",
    str_detect(leaf_10X_cell_type, "Epi") ~ "E",
    str_detect(leaf_10X_cell_type, "IP") ~ "IP",
    str_detect(leaf_10X_cell_type, "Idio") ~ "I",
    str_detect(leaf_10X_cell_type, "Vas") ~ "V",
    str_detect(leaf_10X_cell_type, "GC") ~ "GC",
    str_detect(leaf_10X_cell_type, "Unassigned") ~ "Un"
  )) %>% 
  mutate(Drop_tag = case_when(
    str_detect(Drop_seq_cell_type, "Meso") ~ "M",
    str_detect(Drop_seq_cell_type, "Epi") ~ "E",
    str_detect(Drop_seq_cell_type, "IP") ~ "IP",
    str_detect(Drop_seq_cell_type, "Idio") ~ "I",
    str_detect(Drop_seq_cell_type, "Vas") ~ "V",
    str_detect(Drop_seq_cell_type, "Guard") ~ "GC",
    str_detect(Drop_seq_cell_type, "CC") ~ "CC"
  )) %>% 
  mutate(TenX_tag = factor(TenX_tag, levels = c(
    "M", "E", "V", "IP", "I", "GC", "Un"
  ))) %>% 
  mutate(Drop_tag = factor(Drop_tag, levels = c(
    "M", "E", "IP", "I"
  ))) %>% 
  mutate(Drop_tag = fct_rev(Drop_tag)) %>% 
  ggplot(aes(x = TenX_tag, y = Drop_tag)) +
  geom_tile(aes(fill = Cor)) +
  scale_fill_viridis(option = "D",
                       breaks = c(-0.9, 0, 0.9),
                     limits = c(-1, 1)) +
  labs(x = "10x cell types",
       y = "Drop-seq cell types",
       fill = "r") +
  theme_classic() +
  theme(
    text = element_text(size = 14, color = "black"),
    axis.text = element_text(color = "black"),
    legend.position = "right"
  )

ggsave("../Results/R_output_Leaf_scRNAseq/DropSeq_vs_10x.svg", height = 2.25, width = 3.5, bg = "white")
ggsave("../Results/R_output_Leaf_scRNAseq/DropSeq_vs_10x.png", height = 2.25, width = 3.5, bg = "white")
```
```{r}
View(Dropseq_vs_10X)
```

